---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- include_vars: group_vars/hortonworks
  when: distro == "hdp"

- name: Install libselinux-python required for ansible
  yum:
    name: libselinux-python
    state: present
    update_cache: yes
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: Install epel-release
  yum:
    name: "{{ epel_yum }}"
    state: present
    update_cache: yes
  ignore_errors: true
  register: epel_result
  when: ansible_os_family == "RedHat"

- name: Install epel-release (rpm)
  yum:
    name: "{{ epel_rpm_url }}"
    state: present
  when: ansible_os_family == "RedHat" and epel_result|failed

- name: Configure EPEL repo without mirrors
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo

- name: Ensure required packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items: "{{ packages|default([]) }}"
  when: ansible_os_family == "RedHat"

- name: Set nofile limits
  lineinfile: dest=/etc/security/limits.conf
              insertbefore="^# End of file"
              state=present
              line="{{ item }}"
  with_items:
    - "* soft nofile 32768"
    - "* hard nofile 32768"
  when: not azure

- name: Set nproc limits
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf
              insertafter=EOF
              state=present
              create=yes
              line="{{ item }}"
              mode=0644
  with_items:
    - "* soft nproc 32768"
    - "* hard nproc 32768"
  when: not azure

- name: Set swappiness to 1
  sysctl: name=vm.swappiness value=1 state=present ignoreerrors=yes

- name: Set the tuned profile
  copy: src=tuned.conf
        dest=/etc/tuned/hadoop/
        mode=0755
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Activate the tuned profile
  shell: tuned-adm profile hadoop
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Get number of kernels in grub.conf
  shell: grep -E "^[[:blank:]]*kernel" /boot/grub/grub.conf | grep -v transparent_hugepage; exit 0
  register: grep_result
  when: ansible_os_family == "RedHat" and (ansible_distribution == "Amazon" or ansible_distribution_major_version == "6") and not azure
  ignore_errors: true

- name: Disable Transparent Huge Pages in Grub 1
  lineinfile: dest=/boot/grub/grub.conf
              backrefs=True
              state=present
              regexp='(^\s*kernel(\s+(?!transparent_hugepage=never)[\w=/\-\.\,]+)*)\s*$'
              line='\1 transparent_hugepage=never'
  with_items: "{{ grep_result.stdout_lines | default('') }}"
  when: ansible_os_family == "RedHat" and (ansible_distribution == "Amazon" or ansible_distribution_major_version == "6") and not azure


- name: Disable Transparent Huge Pages in Grub 2
  lineinfile: dest=/etc/default/grub
              state=present
              line='GRUB_CMDLINE_LINUX=$GRUB_CMDLINE_LINUX" transparent_hugepage=never"'
  when: ansible_distribution_major_version|int > 6 and not azure
  notify: Run update-grub

- meta: flush_handlers

- name: Disable Transparent Huge Pages until reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  ignore_errors: true
  when: not azure

- name: Reconfigure resolv.conf search
  lineinfile: dest={{ resolv_conf }}
              create=yes
              regexp='^search\s+(?! {{ ansible_domain }} ).*$'
              line='search {{ ansible_domain }}'
  when: ansible_domain != "" and not use_dns
  notify: Run resolvconf

- meta: flush_handlers

- name: Configure bonding
  include: bonding.yml
  when: bond_interfaces is defined

- name: Set hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644
  when: not azure

- name: Include firewall.yml
  include: firewall.yml
  when: configure_firewall or rax_id is defined

- name: Include partitioning.yml
  include: partitioning.yml
  with_flattened:
    - "{{ namenode_disk|default([]) }}"
    - "{{ masterservices_disk|default([]) }}"
    - "{{ hadoop_disk|default([]) }}"
    - "{{ datanode_disks|default([]) }}"
    - "{{ mysql_disks|default([]) }}"

- name: Mount hadoop disk under /hadoop
  mount: state=mounted
         src="/dev/{{ hadoop_disk }}1"
         name="/hadoop"
         fstype="{{ data_disks_filesystem }}"
         opts=defaults,noatime
         dump=0
         passno=0
  when: hadoop_disk is defined and hadoop_disk and ansible_devices[hadoop_disk] is defined

- name: Mount namenode disk under /hadoop/nn
  mount: state=mounted
         src="/dev/{{ namenode_disk }}1"
         name="/hadoop/nn"
         fstype="{{ data_disks_filesystem }}"
         opts=defaults,noatime
         dump=0
         passno=0
  when: namenode_disk is defined and namenode_disk and ansible_devices[namenode_disk] is defined

- name: Mount master services disk under /hadoop/ms
  mount: state=mounted
         src="/dev/{{ masterservices_disk }}1"
         name="/hadoop/ms"
         fstype="{{ data_disks_filesystem }}"
         opts=defaults,noatime
         dump=0
         passno=0
  when: masterservices_disk is defined and masterservices_disk and ansible_devices[masterservices_disk] is defined

- name: create mysql mount
  file: name=/var/lib/mysql state=directory
  when: mysql_disk is defined and mysql_disk and ansible_devices[mysql_disk] is defined

- name: Mount mysql services disk under /var/lib/mysql
  mount: state=mounted
         src="/dev/{{ mysql_disk }}1"
         name="/var/lib/mysql/"
         fstype="{{ data_disks_filesystem }}"
         opts=defaults,noatime
         dump=0
         passno=0
  when: mysql_disk is defined and mysql_disk and ansible_devices[mysql_disk] is defined

- name: Mount datanode disks under /grid/{0..n}
  mount: state=mounted
         src="/dev/{{ item.1 }}1"
         name="/grid/{{ item.0 }}"
         fstype="{{ data_disks_filesystem }}"
         opts=defaults,noatime
         dump=0
         passno=0
  with_indexed_items: "{{ datanode_disks|default([]) }}"
  when: datanode_disks is defined and datanode_disks and ansible_devices[item.1] is defined

- name: Include cachedisks.yml
  include: cachedisks.yml
  when: software_raid_devices is defined
