---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- include_vars: group_vars/hortonworks
  when: distro == "hdp"

- name: Configure percona repo
  template: src=percona-release.repo.j2 dest=/etc/yum.repos.d/percona-release.repo

- name: Install Percona-Server-server
  yum:
    name: Percona-Server-server-57
    state: present
    update_cache: yes
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: Install mysql-connector-java
  yum:
    name: mysql-connector-java
    state: present
    update_cache: yes
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: Create mysql bootstrap file that will create ambari user
  template: src=mysql-init.j2 dest=/tmp/mysql-init owner=mysql group=mysql

- name: Configure mysql-init file
  lineinfile: dest=/etc/percona-server.conf.d/mysqld.cnf
              regexp='^init-file\s*='
              line='init-file=/tmp/mysql-init'
              state=present

- name: Start mysql service
  command: service mysql start

- name: Create ambari db and schema
  shell: mysql -h localhost -P 3306 -u ambari -p {{ services_password }} ambari < /var/lib/ambari-server/resources/Ambari-DDL-MySQL-CREATE.sql
