---
- name: Reload systemd
  command: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Restart ambari-server
  become: true
  become_user: ambari
  service: name=ambari-server state=restarted
