---
- name: Upload 3-masternodes blueprint
  template: src=blueprint-multi-node-3-masters.j2 dest=/tmp/cluster_blueprint mode=0644
  when: groups['master-nodes']|length > 2

- name: Upload cluster creation template
  template: src=cluster-template-multi-nodes.j2 dest=/tmp/cluster_template mode=0644
